### ISSUE TITLE
Downloads start but do not finish

### ISSUE THREAD

**Issue by araujoanderson** [UncleJunVIP/Mortar.pak#17]
Hello, 

First of all, thanks for such a handy tool.

The issue I'm seeing is that I get the roms lists from the megathread and the downloads start but they stop with the error: **"Unable to complete download for xx-rom.zip"**

I'm using the latest version of NextUI (just updated it today) and the Roms path is the default one.

Here's what the **Mortar log  says**(**the first part can be ignored as I shamefully didn't update the URL,** but afterwards then I see errors with trying to create a folder which I suppose it wouldn't need to since the Roms path is the default used on NextUI):

```
{"level":"error","timestamp":"2025-04-14T21:45:57.603-0400","msg":"Error downloading MortarItem List","error":"unable to fetch table:, Get \"https://firstruleoffight.club/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/\": dial tcp: lookup firstruleoffight.club on [::1]:53: read udp [::1]:58522->[::1]:53: read: connection refused"}
{"level":"error","timestamp":"2025-04-14T21:46:09.601-0400","msg":"Error downloading MortarItem List","error":"unable to fetch table:, Get \"https://firstruleoffight.club/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/\": dial tcp: lookup firstruleoffight.club on [::1]:53: read udp [::1]:59214->[::1]:53: read: connection refused"}
{"level":"error","timestamp":"2025-04-14T21:48:43.613-0400","msg":"Error downloading MortarItem List","error":"unable to fetch table:, Get \"https://firstruleoffight.club/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/\": dial tcp: lookup firstruleoffight.club on [::1]:53: read udp [::1]:43626->[::1]:53: read: connection refused"}
{"level":"error","timestamp":"2025-04-14T21:48:55.603-0400","msg":"Error downloading MortarItem List","error":"unable to fetch table:, Get \"https://firstruleoffight.club/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/\": dial tcp: lookup firstruleoffight.club on [::1]:53: read udp [::1]:45195->[::1]:53: read: connection refused"}
{"level":"error","timestamp":"2025-04-14T22:36:57.039-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:37:09.007-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:37:31.692-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:37:47.810-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:38:20.943-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}
{"level":"error","timestamp":"2025-04-14T22:38:58.013-0400","msg":"Error downloading file: %s","error":"failed to create directory: mkdir : no such file or directory"}

```

And Here's how the **config.yml** file looks (pretty much the standard from the example just with the https://youknowwhat.secret added)
hosts:

 ```
 - display_name: "Fight Club"
    host_type: MEGATHREAD
    root_uri: "https://mmmmmm.me"

    sections:
      - section_name: "Game Boy"
        system_tag: "GB"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy/"
      - section_name: "Game Boy Color"
        system_tag: "GBC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy%20Color/"
      - section_name: "Game Boy Advance"
        system_tag: "GBA"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Game%20Boy%20Advance/"
      - section_name: "Nintendo Entertainment System"
        system_tag: "FC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Nintendo%20Entertainment%20System%20(Headered)/"
      - section_name: "Super Nintendo Entertainment System"
        system_tag: "SFC"
        host_subdirectory: "/files/No-Intro/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/"
      - section_name: "PlayStation"
        system_tag: "PS"
        host_subdirectory: "/files/Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA/"

    filters:
      - "USA"
      - "En,"

show_item_count: false
download_art: true
log_level: "ERROR"
```

_**P.S. While double reading this I found out the root_uri: what's set with a "/" at the end(  root_uri: "https://mmmmmm.me/"), I removed it and tried again and had the same result**_

I tried manually downloading one of the roms I had tried before and adding it to the SD card and I was able to do so, no issues, so it doesn't look to be a faulty card or anything similar.

Apologies If this is an error on my end (I wouldn't be surprised  if it was) but in case it wasn't I just wanted to provide what I believe could be valuable feedback.
