### ISSUE TITLE
Feature request: boxart downloads

### ISSUE THREAD

**Issue by laesetuc** [UncleJunVIP/Mortar.pak#9]
Hi, just wanted to say thanks for your amazing work again.

Just wondering - would it be possible to add the libretro thumbnails repository on github as a source, and be able to download PNG files?
That way we can grab boxart as well after we get our game files.

For example:

Source:
https://github.com/libretro-thumbnails/Nintendo_-_Game_Boy_Advance/tree/master/Named_Boxarts

```
hosts:
  - display_name: "Libretro Thumbnails"
    host_type: GITHUB
    root_uri: "https://github.com/libretro-thumbnails"

    sections:
      - section_name: "Game Boy Advance"
        host_subdirectory: "/Nintendo_-_Game_Boy_Advance/tree/master/Named_Boxarts/"
        local_directory: "/mnt/SDCARD/Roms/Game Boy Advance (MGBA)/.media/"
```
